-- Create table variable
/* CREATE TABLE currencies (
  id bigint(20) unsigned,
  name   VARCHAR(20),
  code   VARCHAR(3),
  symbol VARCHAR(5)
);
 */
ALTER TABLE currencies CONVERT TO CHARACTER SET utf8;

-- Insert currencies records
INSERT INTO currencies (id,name, code, symbol) VALUES ('1','Albanian Leke', 'ALL', 'Lek');
INSERT INTO currencies (id,name, code, symbol) VALUES ('2','US Dollars', 'USD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('3','Afghan Afghanis', 'AFN', '؋');
INSERT INTO currencies (id,name, code, symbol) VALUES ('4','Argentinian Pesos', 'ARS', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('5','Aruban Guilders', 'AWG', 'ƒ');
INSERT INTO currencies (id,name, code, symbol) VALUES ('6','Australian Dollars', 'AUD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('7','Azerbaijani New Manats', 'AZN', 'ман');
INSERT INTO currencies (id,name, code, symbol) VALUES ('8','Bahamian Dollars', 'BSD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('9','Barbadian Dollars', 'BBD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('10','Belarusian Rubles', 'BYR', 'p.');
INSERT INTO currencies (id,name, code, symbol) VALUES ('11','Euro', 'EUR', '€');
INSERT INTO currencies (id,name, code, symbol) VALUES ('12','Belizean Dollars', 'BZD', 'BZ$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('13','Bermudian Dollars', 'BMD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('14','Bolivian Bolivianos', 'BOB', '$b');
INSERT INTO currencies (id,name, code, symbol) VALUES ('15','Bosnia and Herzegovina Convertible Marka', 'BAM', 'KM');
INSERT INTO currencies (id,name, code, symbol) VALUES ('16','Botswana Pula', 'BWP', 'P');
INSERT INTO currencies (id,name, code, symbol) VALUES ('17','Bulgarian Leva', 'BGN', 'лв');
INSERT INTO currencies (id,name, code, symbol) VALUES ('18','Brazilian Reais', 'BRL', 'R$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('19','British Pounds', 'GBP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('20','Brunei Dollars', 'BND', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('21','Cambodian Riels', 'KHR', '៛');
INSERT INTO currencies (id,name, code, symbol) VALUES ('22','Canadian Dollars', 'CAD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('23','Cayman Islands Dollars', 'KYD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('24','Chilean Pesos', 'CLP', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('25','Chinese Yuan Renminbi', 'CNY', '¥');
INSERT INTO currencies (id,name, code, symbol) VALUES ('26','Colombian Pesos', 'COP', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('27','Costa Rican Colón', 'CRC', '₡');
INSERT INTO currencies (id,name, code, symbol) VALUES ('28','Croatian Kuna', 'HRK', 'kn');
INSERT INTO currencies (id,name, code, symbol) VALUES ('29','Cuban Pesos', 'CUP', '₱');
INSERT INTO currencies (id,name, code, symbol) VALUES ('30','Czech Koruny', 'CZK', 'Kč');
INSERT INTO currencies (id,name, code, symbol) VALUES ('31','Danish Kroner', 'DKK', 'kr');
INSERT INTO currencies (id,name, code, symbol) VALUES ('32','Dominican Pesos', 'DOP ', 'RD$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('33','East Caribbean Dollars', 'XCD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('34','Egyptian Pounds', 'EGP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('35','Salvadoran Colones', 'SVC', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('36','Falkland Islands Pounds', 'FKP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('37','Fijian Dollars', 'FJD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('38','Ghanaian Cedis', 'GHC', '¢');
INSERT INTO currencies (id,name, code, symbol) VALUES ('39','Gibraltar Pounds', 'GIP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('40','Guatemalan Quetzales', 'GTQ', 'Q');
INSERT INTO currencies (id,name, code, symbol) VALUES ('41','Guernsey Pounds', 'GGP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('42','Guyanese Dollars', 'GYD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('43','Honduran Lempiras', 'HNL', 'L');
INSERT INTO currencies (id,name, code, symbol) VALUES ('44','Hong Kong Dollars', 'HKD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('45','Hungarian Forint', 'HUF', 'Ft');
INSERT INTO currencies (id,name, code, symbol) VALUES ('46','Icelandic Kronur', 'ISK', 'kr');
INSERT INTO currencies (id,name, code, symbol) VALUES ('47','Indian Rupees', 'INR', '₹');
INSERT INTO currencies (id,name, code, symbol) VALUES ('48','Indonesian Rupiahs', 'IDR', 'Rp');
INSERT INTO currencies (id,name, code, symbol) VALUES ('49','Iranian Rials', 'IRR', '﷼');
INSERT INTO currencies (id,name, code, symbol) VALUES ('50','Isle of Man Pounds', 'IMP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('51','Israeli New Shekels', 'ILS', '₪');
INSERT INTO currencies (id,name, code, symbol) VALUES ('52','Jamaican Dollars', 'JMD', 'J$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('53','Japanese Yen', 'JPY', '¥');
INSERT INTO currencies (id,name, code, symbol) VALUES ('54','Jersey Pounds', 'JEP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('55','Kazakhstani Tenge', 'KZT', 'лв');
INSERT INTO currencies (id,name, code, symbol) VALUES ('56','North Korean Won', 'KPW', '₩');
INSERT INTO currencies (id,name, code, symbol) VALUES ('57','South Korean Won', 'KRW', '₩');
INSERT INTO currencies (id,name, code, symbol) VALUES ('58','Kyrgyzstani Soms', 'KGS', 'лв');
INSERT INTO currencies (id,name, code, symbol) VALUES ('59','Lao Kips', 'LAK', '₭');
INSERT INTO currencies (id,name, code, symbol) VALUES ('60','Latvian Lati', 'LVL', 'Ls');
INSERT INTO currencies (id,name, code, symbol) VALUES ('61','Lebanese Pounds', 'LBP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('62','Liberian Dollars', 'LRD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('63','Swiss Francs', 'CHF', 'CHF');
INSERT INTO currencies (id,name, code, symbol) VALUES ('64','Lithuanian Litai', 'LTL', 'Lt');
INSERT INTO currencies (id,name, code, symbol) VALUES ('65','Macedonian Denars', 'MKD', 'ден');
INSERT INTO currencies (id,name, code, symbol) VALUES ('66','Malaysian Ringgits', 'MYR', 'RM');
INSERT INTO currencies (id,name, code, symbol) VALUES ('67','Mauritian Rupees', 'MUR', '₨');
INSERT INTO currencies (id,name, code, symbol) VALUES ('68','Mexican Pesos', 'MXN', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('69','Mongolian Tugriks', 'MNT', '₮');
INSERT INTO currencies (id,name, code, symbol) VALUES ('70','Mozambican Meticais', 'MZN', 'MT');
INSERT INTO currencies (id,name, code, symbol) VALUES ('71','Namibian Dollars', 'NAD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('72','Nepalese Rupees', 'NPR', '₨');
INSERT INTO currencies (id,name, code, symbol) VALUES ('73','Netherlands Antillean Guilders', 'ANG', 'ƒ');
INSERT INTO currencies (id,name, code, symbol) VALUES ('74','New Zealand Dollars', 'NZD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('75','Nicaraguan Cordobas', 'NIO', 'C$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('76','Nigerian Nairas', 'NGN', '₦');
INSERT INTO currencies (id,name, code, symbol) VALUES ('77','Norwegian Kroner', 'NOK', 'kr');
INSERT INTO currencies (id,name, code, symbol) VALUES ('78','Omani Rials', 'OMR', '﷼');
INSERT INTO currencies (id,name, code, symbol) VALUES ('79','Pakistani Rupees', 'PKR', '₨');
INSERT INTO currencies (id,name, code, symbol) VALUES ('80','Panamanian Balboa', 'PAB', 'B/.');
INSERT INTO currencies (id,name, code, symbol) VALUES ('81','Paraguayan Guarani', 'PYG', 'Gs');
INSERT INTO currencies (id,name, code, symbol) VALUES ('82','Peruvian Nuevos Soles', 'PEN', 'S/.');
INSERT INTO currencies (id,name, code, symbol) VALUES ('83','Philippine Pesos', 'PHP', 'Php');
INSERT INTO currencies (id,name, code, symbol) VALUES ('84','Polish Zlotych', 'PLN', 'zł');
INSERT INTO currencies (id,name, code, symbol) VALUES ('85','Qatari Rials', 'QAR', '﷼');
INSERT INTO currencies (id,name, code, symbol) VALUES ('86','Romanian New Lei', 'RON', 'lei');
INSERT INTO currencies (id,name, code, symbol) VALUES ('87','Russian Rubles', 'RUB', 'руб');
INSERT INTO currencies (id,name, code, symbol) VALUES ('88','Saint Helena Pounds', 'SHP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('89','Saudi Riyals', 'SAR', '﷼');
INSERT INTO currencies (id,name, code, symbol) VALUES ('90','Serbian Dinars', 'RSD', 'Дин.');
INSERT INTO currencies (id,name, code, symbol) VALUES ('91','Seychellois Rupees', 'SCR', '₨');
INSERT INTO currencies (id,name, code, symbol) VALUES ('92','Singapore Dollars', 'SGD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('93','Solomon Islands Dollars', 'SBD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('94','Somali Shillings', 'SOS', 'S');
INSERT INTO currencies (id,name, code, symbol) VALUES ('95','South African Rand', 'ZAR', 'R');
INSERT INTO currencies (id,name, code, symbol) VALUES ('96','Sri Lankan Rupees', 'LKR', '₨');
INSERT INTO currencies (id,name, code, symbol) VALUES ('97','Swedish Kronor', 'SEK', 'kr');
INSERT INTO currencies (id,name, code, symbol) VALUES ('98','Surinamese Dollars', 'SRD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('99','Syrian Pounds', 'SYP', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('100','New Taiwan Dollars', 'TWD', 'NT$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('101','Thai Baht', 'THB', '฿');
INSERT INTO currencies (id,name, code, symbol) VALUES ('102','Trinidad and Tobago Dollars', 'TTD', 'TT$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('103','Turkish Lira', 'TRY', '₺');
INSERT INTO currencies (id,name, code, symbol) VALUES ('104','Old Turkish Liras', 'TRL', '£');
INSERT INTO currencies (id,name, code, symbol) VALUES ('105','Tuvaluan Dollars', 'TVD', '$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('106','Ukrainian Hryvnia', 'UAH', '₴');
INSERT INTO currencies (id,name, code, symbol) VALUES ('107','Uruguayan Pesos', 'UYU', '$U');
INSERT INTO currencies (id,name, code, symbol) VALUES ('108','Uzbekistani Sums', 'UZS', 'лв');
INSERT INTO currencies (id,name, code, symbol) VALUES ('109','Venezuelan Bolivares Fuertes', 'VEF', 'Bs');
INSERT INTO currencies (id,name, code, symbol) VALUES ('110','Vietnamese Dong', 'VND', '₫');
INSERT INTO currencies (id,name, code, symbol) VALUES ('111','Yemeni Rials', 'YER', '﷼');
INSERT INTO currencies (id,name, code, symbol) VALUES ('112','Zimbabwean Dollars', 'ZWD', 'Z$');
INSERT INTO currencies (id,name, code, symbol) VALUES ('113','Indian Rupees', 'INR', '₹');
INSERT INTO currencies (id, name, code, symbol) VALUES ('114', 'Angolan Kwanza', 'AOA', 'Kz');
INSERT INTO currencies (id, name, code, symbol) VALUES ('115', 'Armenian Dram', 'AMD', '֏');
INSERT INTO currencies (id, name, code, symbol) VALUES ('116', 'Bhutanese Ngultrum', 'BTN', 'Nu.');
INSERT INTO currencies (id, name, code, symbol) VALUES ('117', 'Central African CFA Franc', 'XAF', 'FCFA');
INSERT INTO currencies (id, name, code, symbol) VALUES ('118', 'Congolese Franc', 'CDF', 'FC');
INSERT INTO currencies (id, name, code, symbol) VALUES ('119', 'Djiboutian Franc', 'DJF', 'Fdj');
INSERT INTO currencies (id, name, code, symbol) VALUES ('120', 'Eritrean Nakfa', 'ERN', 'Nfk');
INSERT INTO currencies (id, name, code, symbol) VALUES ('121', 'Ethiopian Birr', 'ETB', 'Br');
INSERT INTO currencies (id, name, code, symbol) VALUES ('122', 'Georgian Lari', 'GEL', '₾');
INSERT INTO currencies (id, name, code, symbol) VALUES ('123', 'Guinean Franc', 'GNF', 'FG');
INSERT INTO currencies (id, name, code, symbol) VALUES ('124', 'Iraqi Dinar', 'IQD', 'ع.د');
INSERT INTO currencies (id, name, code, symbol) VALUES ('125', 'Jordanian Dinar', 'JOD', 'د.ا');
INSERT INTO currencies (id, name, code, symbol) VALUES ('126', 'Kuwaiti Dinar', 'KWD', 'د.ك');
INSERT INTO currencies (id, name, code, symbol) VALUES ('127', 'Libyan Dinar', 'LYD', 'ل.د');
INSERT INTO currencies (id, name, code, symbol) VALUES ('128', 'Malagasy Ariary', 'MGA', 'Ar');
INSERT INTO currencies (id, name, code, symbol) VALUES ('129', 'Maldivian Rufiyaa', 'MVR', 'Rf');
INSERT INTO currencies (id, name, code, symbol) VALUES ('130', 'Mauritanian Ouguiya', 'MRU', 'UM');
INSERT INTO currencies (id, name, code, symbol) VALUES ('131', 'Moldovan Leu', 'MDL', 'L');
INSERT INTO currencies (id, name, code, symbol) VALUES ('132', 'Moroccan Dirham', 'MAD', 'د.م.');
INSERT INTO currencies (id, name, code, symbol) VALUES ('133', 'Myanmar Kyat', 'MMK', 'Ks');
INSERT INTO currencies (id, name, code, symbol) VALUES ('134', 'Papua New Guinean Kina', 'PGK', 'K');
INSERT INTO currencies (id, name, code, symbol) VALUES ('135', 'Rwandan Franc', 'RWF', 'FRw');
INSERT INTO currencies (id, name, code, symbol) VALUES ('136', 'Samoan Tala', 'WST', 'T');
INSERT INTO currencies (id, name, code, symbol) VALUES ('137', 'São Tomé and Príncipe Dobra', 'STN', 'Db');
INSERT INTO currencies (id, name, code, symbol) VALUES ('138', 'Sierra Leonean Leone', 'SLL', 'Le');
INSERT INTO currencies (id, name, code, symbol) VALUES ('139', 'Somoni', 'TJS', 'ЅМ');
INSERT INTO currencies (id, name, code, symbol) VALUES ('140', 'Tanzanian Shilling', 'TZS', 'TSh');
INSERT INTO currencies (id, name, code, symbol) VALUES ('141', 'Tongan Paʻanga', 'TOP', 'T$');
INSERT INTO currencies (id, name, code, symbol) VALUES ('142', 'Turkmenistani Manat', 'TMT', 'm');
INSERT INTO currencies (id, name, code, symbol) VALUES ('143', 'Ugandan Shilling', 'UGX', 'USh');
INSERT INTO currencies (id, name, code, symbol) VALUES ('144', 'Zambian Kwacha', 'ZMW', 'ZK');

